version: 2
jobs:
  build:
    docker:
      - image: openjdk:11
    environment:
      SBT_VERSION: 1.3.12
    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: sbt バイナリを取得
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
            apt-get update
            apt-get install -y python-pip git
            pip install awscli
            apt-get clean && apt-get autoclean
      - checkout
      - setup_remote_docker
      - run:
          name: dockerコンテナ起動
          command: |
            set -x
            docker-compose up -d
      - restore_cache:
          key: v1-sbt-cache
      - run:
          name: build
          command: cat /dev/null | sbt compile
      - run:
          name: check code format
          command: cat /dev/null | sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
      - run:
          name: test
          command: cat /dev/null | sbt test
      - save_cache:
          key: v1-sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

